spring:
  profiles:
    active: chaos-monkey

chaos:
  monkey:
    watcher:
      component: false
      controller: false
      repository: false
      rest-controller: true
      service: true
    assaults:
      latency-active: true
      latency-range-start: 30000
      latency-range-end: 150000
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus