management:
  server:
    port: 8029
    security:
      enabled: false

chaos:
  monkey:
    enabled: true
    watcher:
      rest-controller: true
    assaults:
      latency-active: true
      latency-range-start: 30000
      latency-range-end: 150000