spring:
  profiles:
    active: chaos-monkey

chaos:
  monkey:
    watcher:
      component: false
      controller: false
      repository: false
      rest-controller: true
      service: true
    assaults:
      latency-active: true
      latency-range-start: 300000
      latency-range-end: 1500000
    enabled: true

management:
  endpoint:
    chaosmonkey:
      enabled: true
