management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,chaosmonkey

chaos:
  monkey:
    watcher:
      component: false
      controller: false
      repository: false
      rest-controller: true
      service: true
    assaults:
      latency-active: true
      latency-range-start: 300000
      latency-range-end: 1500000
    enabled: true

spring:
  profiles:
    active: chaos-monkey